# Generated by Django 4.0.3 on 2024-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closest_parking_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='가까운 주차장 주소'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closest_parking_latitude',
            field=models.FloatField(blank=True, default='37.5445023983984', verbose_name='가까운주차장 위도'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closest_parking_longitude',
            field=models.FloatField(blank=True, default='127.056090471223', verbose_name='가까운주차장 경도'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closest_parking_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='가까운 주차장'),
        ),
    ]
