# Generated by Django 4.0.3 on 2024-06-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='imgfile_1',
            new_name='img_file1',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='imgfile_2',
            new_name='img_file2',
        ),
    ]
